# Generated by Django 4.0.3 on 2022-03-17 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodpreasure',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='glucose',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='pulse',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='bloodpreasure',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='glucose',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
