# Generated by Django 4.0.3 on 2022-03-17 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_alter_bloodpreasure_options_alter_glucose_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpreasure',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='glucose',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pulse',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
