# Generated by Django 4.0.3 on 2022-03-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_alter_bloodpreasure_created_alter_glucose_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpreasure',
            name='category',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
