# Generated by Django 4.0.3 on 2022-03-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_bloodpreasure_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpreasure',
            name='category',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
