# Generated by Django 4.0.3 on 2022-03-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_alter_bloodpreasure_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glucose',
            name='glucose',
        ),
        migrations.AddField(
            model_name='glucose',
            name='category',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='glucose',
            name='glucose_blood',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glucose',
            name='glucose_oral',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
