# Generated by Django 4.0.3 on 2022-03-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0007_alter_glucose_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulse',
            name='category',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
